^https?:\/\/.*pangolin.*\/ url reject
^https?:\/\/.*pglstatp-toutiao.*\/ url reject
^https?:\/\/.*ad\.toutiao.*\/ url reject
^https?:\/\/(.*\.)?pangolin-sdk-toutiao(-b)?\.com\/ url reject
^https?:\/\/(is|bds)\.snssdk\.com\/ url reject
^https?:\/\/.*\.snssdk\.com\/api\/ad\/ url reject-dict
^https?:\/\/.*\.snssdk\.com\/api\/ad\/splash\/ url reject-dict
^https?:\/\/.*\.byteimg\.com\/ad-app-icon\/ url reject-img
